import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const view = fs.readFileSync(new URL("../js/publications/PublicationView.js", import.meta.url), "utf8");
const runtime = fs.readFileSync(new URL("../js/telegram/TelegramRuntime.js", import.meta.url), "utf8");
const service = fs.readFileSync(new URL("../js/telegram/PublicationTargetService.js", import.meta.url), "utf8");
const panel = fs.readFileSync(new URL("../js/editor/EditorRightPanel.js", import.meta.url), "utf8");
const publicationService = fs.readFileSync(new URL("../js/telegram/PublicationService.js", import.meta.url), "utf8");
const client = fs.readFileSync(new URL("../js/telegram/TelegramClient.js", import.meta.url), "utf8");
const cleaner = fs.readFileSync(new URL("../js/telegram/TelegramServiceMessageCleaner.js", import.meta.url), "utf8");
const core = fs.readFileSync(new URL("../js/telegram/TelegramCore.js", import.meta.url), "utf8");

assert.match(html, /id="publicationsApp"/);
assert.match(view, /t\("publications\.publicationView\.addChannelGroup"\)/);
for (const key of ["editor.blockPalette.all", "publications.publicationView.channels", "publications.publicationView.groups"]) assert.ok(view.includes(`t("${key}")`));
assert.match(view, /publication-target-members[\s\S]*?👥/);
assert.match(view, /publication-target-posts[\s\S]*?📰/);
assert.match(view, /countPublishedPosts\(this\.publications, target\.chatId\)/);
assert.match(view, /publication-target-comments[\s\S]*?connected[\s\S]*?disconnected/);
assert.match(view, /t\("publications\.publicationView\.commentGroupConnected"\)/);
assert.match(view, /t\("publications\.publicationView\.deleteService"\)/);
assert.match(view, /publication-target-cleanup\$\{cleanupEnabled \? " active" : ""\}/);
assert.match(view, /cleanup\.setAttribute\("aria-pressed"/);
assert.match(view, /setServiceMessageCleanup\(target\.chatId, enabled\)/);
assert.doesNotMatch(view, /button\("×", \(\) => this\.telegramCore\.publications\.removeTarget/);
assert.match(runtime, /publicationTargets\?\.handleMyChatMember/);
assert.match(service, /t\("telegram\.publicationTargetService\.previewChannelCannotBeAddedToPublications"\)/);
assert.match(service, /deleteServiceMessages: existing\?\.deleteServiceMessages === true/);
assert.match(core, /setServiceMessageCleanup: \(chatId, enabled\)/);
assert.match(cleaner, /directTarget\?\.deleteServiceMessages === true/);
assert.match(cleaner, /target\.deleteServiceMessages === true[\s\S]*?target\.linkedDiscussionChatId/);
assert.match(view, /key: "publicationsLeft"/);
assert.match(view, /key: "publicationsRight"/);
assert.match(view, /selectedPublicationId = null/);
assert.match(view, /#normalizePublicationSelection/);
assert.match(view, /#publicationPostPanel/);
assert.match(view, /t\("publications\.publicationView\.dataOfSelectedPost"\)/);
assert.match(view, /publication-record-card\$\{selected \? " selected" : ""\}/);
assert.match(view, /draft:session-changed/);
assert.match(view, /#isEditingPublication/);
assert.match(view, /editor-active/);
for (const key of ["published", "scheduled", "allTime", "today", "7Days", "month", "customRange"]) {
  assert.ok(view.includes(`publications.publicationView.${key}`), `${key} filter missing`);
}
assert.match(view, /input\.type = "date"/);
assert.match(view, /#projectFilterRow/);
assert.match(view, /publishedProjectOptions\(this\.publications, this\.selectedTargetId\)/);
assert.match(view, /scroller\.scrollLeft \+= event\.deltaY/);
assert.match(view, /\{ passive: false \}/);
assert.match(view, /#showPublishDraftDialog/);
assert.match(view, /t\("publications\.publicationView\.commentsEnabled"\)/);
assert.match(view, /t\("publications\.publicationView\.disableComments"\)/);
assert.match(view, /commentsEnabled: !disableComments\.checked/);
assert.match(view, /t\("publications\.publicationView\.delayPublication"\)/);
assert.match(view, /t\("core\.propertyRegistry\.dateAndTime"\)/);
assert.match(view, /t\("publications\.publicationView\.comments"\)/);
assert.match(view, /requestProjectPostSchedule/);
assert.match(view, /requestDraftSchedule/);
assert.match(view, /scheduleDraft\(draft\.id, targetChatId/);
assert.match(view, /cancelDraftSchedule\(record\.id\)/);
assert.match(view, /t\("publications\.publicationView\.editScheduledPostInEditor"\)/);
assert.doesNotMatch(view, /comments\.disabled = commentsField\.hidden \|\| target\?\.discussionRights/);
assert.match(view, /await this\.telegramCore\.publications\.refreshTarget\(targetChatId\)/);
assert.match(view, /publication-record-open/);
assert.match(view, /publication-record-pin/);
assert.match(view, /tools\.append\(edit, link, pin, open, remove\)/);
assert.match(view, /record\.pinned \? t\("publications\.publicationView\.unpinPost"\) : t\("publications\.publicationView\.pinPost"\)/);
assert.match(view, /pin\.setAttribute\("aria-pressed"/);
assert.match(view, /publication-record-edit/);
assert.match(view, /publication-record-delete/);
assert.match(view, /await this\.telegramCore\.publications\.delete\(record\.id\)[\s\S]*?this\.publications = await this\.telegramCore\.publications\.list\(\)/);
assert.match(view, /#isProjectSourceMissing/);
assert.match(view, /record\.source\?\.kind === "project" && !projectMissing/,
  "an orphaned Project publication must fall back to the ordinary publication cleanup path");
assert.match(view, /publication-comment-badge/);
assert.match(view, /const comments = button\("💬"/);
assert.match(view, /record\.discussionUsername[\s\S]*?openPublicMessage/);
assert.match(view, /openPrivateMessage\?\.\(\{ chatId: record\.discussionChatId, messageId: record\.discussionMessageId \}\)/);
assert.doesNotMatch(view, /commentId: record\.discussionMessageId/,
  "the auto-forwarded discussion root is not a comment ID and must not be used as Telegram's comment parameter");
assert.doesNotMatch(view, /`💬 \$\{Number\(record\.commentCount/);
assert.match(view, /reactionEmoji\(reaction\.type\)/);
assert.match(view, /publication-reaction-row/);
assert.match(view, /reactionRow\.append\(badge\)/);
assert.match(panel, /await this\.documents\?\.saveCurrentContext\?\.\(\)/);
assert.match(panel, /this\.onPublishDraft\(fresh\)/);
assert.match(panel, /this\.onScheduleDraft\(fresh\)/);
assert.match(panel, /activeDraft\?\.source\?\.kind === "publication"\) rows = \[activeDraft\]/);
assert.match(panel, /onApplyChanges: draft => this\.#applyDraftChanges\(draft\)/);
assert.match(panel, /onCancelPublicationEdit: draft => this\.#cancelPublicationEdit\(draft\)/);
assert.match(panel, /documents\?\.discardDraft\?\.\(draft\.id/);
assert.match(panel, /#finishPublicationEdit\(draft, "publication-edit-applied"\)/);
assert.match(view, /publication-target-discussion/);
assert.match(view, /target\.linkedDiscussionTitle \|\| t\("publications\.publicationView\.discussionGroup"\)/);
assert.match(view, /incompleteChannels[\s\S]*?refreshTarget/);
assert.match(view, /visibility === "public" \? t\("publications\.publicationView\.public"\) : t\("publications\.publicationView\.private"\)/);
assert.match(publicationService, /this\.#reconcilePendingForward\(record\)\.catch/);
assert.match(publicationService, /async setPinned\(recordId, pinned\)/);
assert.match(publicationService, /record\.discussionChatId[\s\S]*record\.discussionMessageId/);
assert.match(publicationService, /for \(const message of changed\.reverse\(\)\)/,
  "a partial channel/discussion pin operation must be rolled back");
assert.match(client, /unpinChatMessage\(chatId, messageId, options\)/);
assert.match(view, /discussionPending[\s\S]*pin\.disabled = scheduled \|\| discussionPending/);

console.log("publications UI contract smoke: OK");
