import { buildSemanticRichText, defaultDateTimeLocal, listAnchors } from "../core/SemanticRichText.js?v=1.5.9";
import { createDateTimePicker } from "./DateTimePicker.js?v=1.5.9";

export class BlockPalette {
  constructor({ root, categoryRoot = null, registry, metaRegistry = null, controller, dragState = null, richTextContext = null, projectContext = null }) {
    this.root = root;
    this.categoryRoot = categoryRoot;
    this.registry = registry;
    this.metaRegistry = metaRegistry;
    this.controller = controller;
    this.dragState = dragState || { nodeId: "", type: "", source: "" };
    this.richTextContext = richTextContext || { active: null };
    this.projectContext = projectContext;
    this.search = "";
    this.category = "all";
  }

  render() {
    this.root.innerHTML = "";
    const available = this.availableBlocks();
    this.renderCategoryFilters(available);
    const groups = new Map();
    for (const b of this.registry.search(this.search)) {
      if (!available.includes(b)) continue;
      if (this.category !== "all" && (b.category || "Other") !== this.category) continue;
      if (!groups.has(b.category || "Other")) groups.set(b.category || "Other", []);
      groups.get(b.category || "Other").push(b);
    }
    for (const [category, blocks] of groups) {
      if (category === "Content") blocks.sort(compareContentBlocks);
    }

    for (const [category, blocks] of groups) {
      const title = document.createElement("div");
      title.className = "category";
      title.textContent = category;
      this.root.append(title);

      for (const b of blocks) {
        const el = document.createElement("div");
        el.className = "palette-item";
        el.draggable = true;
        const name = document.createElement("strong");
        name.textContent = b.paletteLabel || b.name;
        const type = document.createElement("span");
        type.textContent = b.type;
        const head = document.createElement("div");
        head.className = "palette-item-head";
        head.append(name);
        if (b.kind === "meta" && this.metaRegistry?.all?.().some(meta => meta.type === b.type)) {
          const remove = document.createElement("button");
          remove.type = "button";
          remove.className = "palette-meta-delete";
          remove.textContent = "🗑";
          remove.title = "Удалить Meta Block";
          remove.onclick = event => {
            event.preventDefault();
            event.stopPropagation();
            this.showMetaDeleteConfirmation(el, b);
          };
          head.append(remove);
        }
        el.append(head, type);
        el.title = b.semantic?.inline
          ? `${b.type} — при активном курсоре вставляется в Paragraph, иначе создаётся блок`
          : `${b.type} — перетащите или нажмите`;
        el.onclick = () => this.activateBlock(b);
        el.ondragstart = e => {
          this.dragState.nodeId = "";
          this.dragState.type = b.type;
          this.dragState.source = "palette";
          e.dataTransfer.effectAllowed = "copy";
          e.dataTransfer.setData("application/x-block-type", b.type);
        };
        el.ondragend = () => {
          if (this.dragState.source === "palette") {
            this.dragState.nodeId = "";
            this.dragState.type = "";
            this.dragState.source = "";
          }
        };
        this.root.append(el);
      }
    }
  }

  showMetaDeleteConfirmation(card, definition) {
    if (card.querySelector?.(":scope > .palette-meta-delete-overlay")) return;
    this.root.querySelector?.(".palette-meta-delete-overlay")?.remove?.();
    const overlay = document.createElement("div");
    overlay.className = "palette-meta-delete-overlay";
    const message = document.createElement("span");
    message.textContent = `Удалить «${definition.name || definition.type}»?`;
    const actions = document.createElement("div");
    const cancel = document.createElement("button");
    cancel.type = "button";
    cancel.textContent = "Отмена";
    cancel.onclick = event => { event.stopPropagation(); overlay.remove(); };
    const remove = document.createElement("button");
    remove.type = "button";
    remove.className = "danger";
    remove.textContent = "Удалить";
    remove.onclick = event => {
      event.stopPropagation();
      this.metaRegistry.remove(definition.type);
      this.render();
    };
    actions.append(cancel, remove);
    overlay.append(message, actions);
    overlay.onclick = event => event.stopPropagation();
    card.append(overlay);
    cancel.focus();
  }

  availableBlocks() {
    return this.registry.search("").filter(b => {
      if (b.paletteHidden) return false;
      // Project Map and Back to Map are generated by the Project structure. They
      // are not ordinary constructor blocks and therefore never appear in Palette.
      if (b.projectVirtual) return false;
      return true;
    });
  }

  renderCategoryFilters(blocks) {
    if (!this.categoryRoot) return;
    const categories = [...new Set(blocks.map(block => block.category || "Other"))];
    if (this.category !== "all" && !categories.includes(this.category)) this.category = "all";
    this.categoryRoot.replaceChildren();
    for (const [value, label] of [["all", "Все"], ...categories.map(category => [category, category])]) {
      const chip = document.createElement("button");
      chip.type = "button";
      chip.className = `palette-category-chip${this.category === value ? " active" : ""}`;
      chip.textContent = label;
      chip.setAttribute("aria-pressed", String(this.category === value));
      chip.onclick = () => {
        this.category = value;
        this.render();
      };
      this.categoryRoot.append(chip);
    }
  }

  activateBlock(definition) {
    const active = this.richTextContext.active;
    if (definition.semantic?.inline && active?.textarea?.isConnected && active.node?.type === "paragraph") {
      this.openSemanticDialog(definition, active);
      return;
    }
    const parentId = this.controller.preferredParentFor(definition.type);
    this.controller.addBlock(definition.type, parentId);
  }

  openSemanticDialog(definition, activeState) {
    const dialog = document.createElement("dialog");
    dialog.className = "semantic-insert-dialog";
    const form = document.createElement("form");
    form.method = "dialog";
    const head = document.createElement("div");
    head.className = "dialog-head";
    const title = document.createElement("strong");
    title.textContent = `Вставить: ${definition.name}`;
    const close = document.createElement("button");
    close.type = "button"; close.textContent = "×";
    close.onclick = () => dialog.close("cancel");
    head.append(title, close);

    const body = document.createElement("div");
    body.className = "semantic-insert-body";
    const values = {};
    const bindings = this.registry.propertyBindings(definition).filter(binding => !binding.readOnly);
    for (const schema of bindings) {
      let value = schema.default ?? "";
      if (definition.type === "date_time" && schema.key === "dateTime") value = defaultDateTimeLocal();
      values[schema.key] = structuredClone(value);
      body.append(this.makeSemanticField(schema, values));
    }

    const error = document.createElement("div");
    error.className = "format-config-error";
    body.append(error);
    const actions = document.createElement("div");
    actions.className = "format-config-actions";
    const cancel = document.createElement("button");
    cancel.type = "button"; cancel.textContent = "Отмена"; cancel.onclick = () => dialog.close("cancel");
    const apply = document.createElement("button");
    apply.type = "button"; apply.className = "primary"; apply.textContent = "Вставить за курсором";
    apply.onclick = () => {
      const missing = bindings.find(schema => schema.required && !String(values[schema.key] ?? "").trim());
      if (missing) { error.textContent = `Заполните: ${missing.label || missing.key}`; return; }
      try {
        const entity = buildSemanticRichText(definition.type, values, this.controller.tree);
        if (!activeState.insertValue?.(entity)) throw new Error("Активное текстовое поле больше недоступно");
        dialog.close("inserted");
      } catch (e) {
        error.textContent = e.message || String(e);
      }
    };
    actions.append(cancel, apply);
    body.append(actions);
    form.append(head, body);
    dialog.append(form);
    document.body.append(dialog);
    dialog.addEventListener("close", () => dialog.remove(), { once: true });
    dialog.showModal();
  }

  makeSemanticField(schema, values) {
    const editor = this.registry.properties?.editorFor(schema) || schema.editor || schema.type;
    const wrap = document.createElement(editor === "datetime-local" ? "div" : "label");
    wrap.className = "semantic-insert-field";
    const label = document.createElement("span");
    label.textContent = schema.label || schema.key;
    let input;
    if (editor === "datetime-local") {
      const picker = createDateTimePicker({
        value: values[schema.key] ?? "",
        label: schema.label || "Дата и время",
        onChange: value => { values[schema.key] = value; }
      });
      wrap.append(label, picker);
      if (schema.hint) { const hint = document.createElement("small"); hint.textContent = schema.hint; wrap.append(hint); }
      return wrap;
    }
    if (editor === "select" || schema.type === "enum") {
      input = document.createElement("select");
      for (const option of schema.options || schema.values || []) {
        const value = typeof option === "object" ? option.value : option;
        const text = typeof option === "object" ? option.label : option;
        const item = document.createElement("option"); item.value = value; item.textContent = text; input.append(item);
      }
    } else if (editor === "anchor-select") {
      input = document.createElement("select");
      const top = document.createElement("option"); top.value = ""; top.textContent = "В начало сообщения"; input.append(top);
      for (const anchor of listAnchors(this.controller.tree)) {
        const item = document.createElement("option"); item.value = anchor.id; item.textContent = `⚓ ${anchor.label}`; input.append(item);
      }
    } else {
      input = document.createElement("input");
      input.type = editor === "datetime-local" ? "datetime-local" : editor === "url" ? "url" : "text";
    }
    input.value = values[schema.key] ?? "";
    input.addEventListener("input", () => { values[schema.key] = input.value; });
    input.addEventListener("change", () => { values[schema.key] = input.value; });
    wrap.append(label, input);
    if (schema.hint) { const hint = document.createElement("small"); hint.textContent = schema.hint; wrap.append(hint); }
    return wrap;
  }
}

function compareContentBlocks(left, right) {
  const priority = type => type === "heading" ? 0 : type === "paragraph" ? 1 : type === "footer" ? 3 : 2;
  return priority(left?.type) - priority(right?.type);
}
